### ISSUE TITLE
The provided example does not work

### ISSUE THREAD

**Issue by ChristopherRabotin** [ContentMine/node-journalTOCs#1]
There is no such method as `awesome`, as details follow.

```
 node jtocs.js 

./jtocs.js:3
journaltocs.awesome();
            ^
TypeError: Object function (email) {
  this.baseURL = 'http://www.journaltocs.ac.uk/api/';
  this.email = email;
  this.userStr = '?user=' + this.email;
} has no method 'awesome'
    at Object.<anonymous> (./jtocs.js:3:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by blahah** [comment]
Good point! that file was auto-generated and will be removed. The actual examples are in the README.md.
